name: booking_app_demo
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter
      
  intl: any
  
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0



flutter:
  generate: true
  
  uses-material-design: true

  assets:
      - images/
      - images/room.jpg
      - images/bali.jpg



  
  