# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.7'
    - run: flutter pub get
    - run: flutter build apk
    - run: flutter build appbundle
    - name: Push to Releases
      uses: ncipollo/release-action@v1
      with: 
        artifacts: "build/app/outputs/flutter-apk/app-release.apk"
        tag: v1.0.${{ github.run_number}}
        token: ${{ secrets.TOKEN }}