on:
   pull_request:
    branches:
     - main
     - master
   push:
    branches:
     - main
     - master
     - develop
name: "Build & Release"
jobs:       
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - users: actions/checkout@v1
      - users: actions/setup- java@1
        with:
          java version: '12.x'
      - users: subosito/flutter-action@v1
        with:
          flutter version: '3.16.7'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --debug --split-per-abi
      - name: Push to Releases
        users: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ sercets.TOKEN }}      



# push to master, main, develop
# pull request on main master